### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by anvaari** [N-Coder/ics_vtimezones#1]
Hi thank for developing this tool. I search for it and it is great to find it. 
But i don't find any usage section in README.md it would be much better if provided.
Thanks

**Comment by N-Coder** [comment]
Feel free to check out the source code to see whether there's anything useful for you:
https://github.com/N-Coder/ics_vtimezones/blob/master/src/ics_vtimezones/__init__.py
This package is mostly ment for providing data files to `ics.py` with an independent release pace, so there's not much usage to document.

**Comment by anvaari** [comment]
Actually, I want add time zone to event object.
Thanks, I will read source code. Can I write usage and send pull request ?

**Comment by N-Coder** [comment]
I guess that shouldn't be neccesary, long-term goal is to use this in `ics.py` to provide a nice (and then also documented) API to easily achieve such things.
